# Generated by Django 6.0.1 on 2026-01-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_skills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
