# Generated by Django 6.0.1 on 2026-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("order",),
            },
        ),
    ]
