# Generated by Django 6.0.1 on 2026-01-24 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_skill"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ("order",)},
        ),
    ]
