# Generated by Django 6.0.1 on 2026-01-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_skill_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="icon",
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
    ]
