# Generated by Django 6.0.1 on 2026-01-31 02:17

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_sociallink_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='skill',
            name='text_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('lang', 'Language'), ('front', 'Frontend'), ('back', 'Backend'), ('db', 'Database')], max_length=10),
        ),
    ]
