# Generated by Django 6.0.1 on 2026-01-31 02:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_skill_bg_color_skill_text_color_alter_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='bg_color',
            field=colorfield.fields.ColorField(blank=True, default='#ffffff', image_field=None, max_length=25, samples=None, verbose_name='Background color'),
        ),
    ]
