# Generated by Django 6.0.1 on 2026-01-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("occupation", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="home/")),
            ],
            options={
                "verbose_name_plural": "Home",
            },
        ),
    ]
