# Generated by Django 6.0.1 on 2026-01-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("pages", "0002_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="social_links",
            field=models.ManyToManyField(to="common.sociallink"),
        ),
    ]
