# Generated by Django 6.0.1 on 2026-01-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contact'),
        ('projects', '0003_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.project'),
        ),
    ]
